### ISSUE TITLE
Compilation of objects in Scala with special access privileges fail to compile

### ISSUE THREAD

**Issue by javeleon** [sbt/zinc#127]
Whenever I try to compile a Java project with inner classes in it using Zinc I get the following stacktrace:

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
java.lang.RuntimeException Failed to find name hashes for com.example.allang.zinc_test.A.Inner
    at scala.sys.package$.error(package.scala:27)
    at sbt.internal.inc.AnalysisCallback.nameHashesForCompanions(Compile.scala:263)
    at sbt.internal.inc.AnalysisCallback.sbt$internal$inc$AnalysisCallback$$analyzeClass(Compile.scala:270)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1$$anonfun$8.apply(Compile.scala:280)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1$$anonfun$8.apply(Compile.scala:280)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.mutable.AbstractSet.map(Set.scala:46)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1.apply(Compile.scala:280)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1.apply(Compile.scala:276)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
    at sbt.internal.inc.AnalysisCallback.addProductsAndDeps(Compile.scala:276)
    at sbt.internal.inc.AnalysisCallback.get(Compile.scala:235)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:79)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:76)
    at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:63)
    at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:37)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:73)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
    at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:101)
    at sbt.internal.inc.Incremental$.compile(Incremental.scala:71)
    at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:59)
    at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:162)
    at sbt.internal.inc.IncrementalCompilerImpl.incrementalCompile(IncrementalCompilerImpl.scala:107)
    at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:51)
    at com.zt.jrebel.android.java.incremental.ZincExecutor.execute(ZincExecutor.java:117)
    at com.zt.jrebel.android.java.incremental.ZincExecutor.execute(ZincExecutor.java:103)
    at com.zt.jrebel.android.java.incremental.SourcePreCompiler.precompileSources(SourcePreCompiler.java:38)
    at com.zt.jrebel.android.java.incremental.JavaIncrementalCompiler.parseIncremental(JavaIncrementalCompiler.java:173)
    at com.zt.jrebel.android.java.incremental.JavaIncrementalCompiler.compile(JavaIncrementalCompiler.java:75)
    at com.zt.jra.bundled.compilation.JrJavacAction.execute(JrJavacAction.java:77)
    at com.zt.jra.bundled.compilation.JrJavacAction.execute(JrJavacAction.java:26)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by gkossakowski** [comment]
Thanks for the report. Does this class exist in your source code? Is `A.Inner` nested in an object?

**Comment by romanowski** [comment]
@javeleon can you confirm that after https://github.com/sbt/zinc/pull/158 is merge this is still a problem?

I faced similar issues and PR above fix them.

**Comment by jvican** [comment]
Hi @javeleon, could you please confirm this issue is fixed? We'd like to close it asap.

**Comment by jvican** [comment]
Closing, if this is still an issue, please reopen. /cc @javeleon

**Comment by fommil** [comment]
I'm getting this with a scala `object` inside a a `class`... the object is `private[EnclosingClass]` if that matters.

**Comment by dwijnand** [comment]
If you have any kind of reproduction (minimised most appreciated) we can reopen (or open a new issue).

**Comment by fommil** [comment]
```scala
class Foo {
  private[Foo] object Bar
}
```

oughta do it (I checked)

**Comment by dwijnand** [comment]
Wow, that's literally enough.

**Comment by jvican** [comment]
Working for a fix to this now. PR will probably happen today.

**Comment by dwijnand** [comment]
Cool, moved to the 1.0.3 milestone then.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/431

**Comment by jvican** [comment]
This is the second time an issue is not closed after a PR referencing to it with "Fix #bla" is merged.
