### ISSUE TITLE
NPE compiling Java code

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#129]
## steps

https://github.com/eed3si9n/zinc-bug-repro
## problem

```
java.lang.NullPointerException
    at sbt.internal.inc.ClassToAPI$.packageAndName(ClassToAPI.scala:352)
    at sbt.internal.inc.ClassToAPI$.reference(ClassToAPI.scala:319)
    at sbt.internal.inc.ClassToAPI$.reference(ClassToAPI.scala:314)
    at sbt.internal.inc.ClassToAPI$.reference(ClassToAPI.scala:340)
    at sbt.internal.inc.ClassToAPI$.parameter(ClassToAPI.scala:234)
    at sbt.internal.inc.ClassToAPI$$anonfun$19.apply(ClassToAPI.scala:223)
    at sbt.internal.inc.ClassToAPI$$anonfun$19.apply(ClassToAPI.scala:223)
    at scala.runtime.Tuple3Zipped$$anonfun$map$extension$1.apply(Tuple3Zipped.scala:44)
    at scala.runtime.Tuple3Zipped$$anonfun$map$extension$1.apply(Tuple3Zipped.scala:42)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.runtime.Tuple3Zipped$.map$extension(Tuple3Zipped.scala:42)
    at sbt.internal.inc.ClassToAPI$.defLike(ClassToAPI.scala:223)
    at sbt.internal.inc.ClassToAPI$.constructorToDef(ClassToAPI.scala:217)
    at sbt.internal.inc.ClassToAPI$$anonfun$9.apply(ClassToAPI.scala:96)
    at sbt.internal.inc.ClassToAPI$$anonfun$9.apply(ClassToAPI.scala:96)
    at sbt.internal.inc.ClassToAPI$$anonfun$mergeMap$1.apply(ClassToAPI.scala:245)
    at sbt.internal.inc.ClassToAPI$$anonfun$mergeMap$1.apply(ClassToAPI.scala:245)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at sbt.internal.inc.ClassToAPI$.merge(ClassToAPI.scala:251)
    at sbt.internal.inc.ClassToAPI$.mergeMap(ClassToAPI.scala:245)
    at sbt.internal.inc.ClassToAPI$.structure(ClassToAPI.scala:96)
    at sbt.internal.inc.ClassToAPI$.x$2$lzycompute$1(ClassToAPI.scala:77)
    at sbt.internal.inc.ClassToAPI$.x$2$1(ClassToAPI.scala:77)
    at sbt.internal.inc.ClassToAPI$.instance$lzycompute$1(ClassToAPI.scala:77)
    at sbt.internal.inc.ClassToAPI$.sbt$internal$inc$ClassToAPI$$instance$1(ClassToAPI.scala:77)
    at sbt.internal.inc.ClassToAPI$$anonfun$5.apply(ClassToAPI.scala:78)
    at sbt.internal.inc.ClassToAPI$$anonfun$5.apply(ClassToAPI.scala:78)
    at xsbti.SafeLazy$Impl._t$lzycompute(SafeLazy.scala:18)
    at xsbti.SafeLazy$Impl._t(SafeLazy.scala:16)
    at xsbti.SafeLazy$Impl.get(SafeLazy.scala:22)
    at sbt.internal.inc.ClassToAPI$$anonfun$process$1.apply(ClassToAPI.scala:24)
    at sbt.internal.inc.ClassToAPI$$anonfun$process$1.apply(ClassToAPI.scala:24)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
    at sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:24)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.sbt$internal$inc$javac$AnalyzingJavaCompiler$$readAPI$1(AnalyzingJavaCompiler.scala:74)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$5.apply(AnalyzingJavaCompiler.scala:84)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$5.apply(AnalyzingJavaCompiler.scala:84)
    at sbt.internal.inc.classfile.Analyze$$anonfun$apply$11.apply(Analyze.scala:65)
    at sbt.internal.inc.classfile.Analyze$$anonfun$apply$11.apply(Analyze.scala:60)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
    at sbt.internal.inc.classfile.Analyze$.apply(Analyze.scala:60)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2.apply(AnalyzingJavaCompiler.scala:84)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2.apply(AnalyzingJavaCompiler.scala:82)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply$mcV$sp(AnalyzingJavaCompiler.scala:82)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply(AnalyzingJavaCompiler.scala:82)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply(AnalyzingJavaCompiler.scala:82)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:81)
    at sbt.internal.inc.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:57)
    at sbt.internal.inc.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:57)
    at sbt.internal.inc.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:57)
    at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:71)
    at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:56)
    at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:61)
    at sbt.internal.inc.IncrementalCompilerImpl$$anonfun$compileInternal$1.apply(IncrementalCompilerImpl.scala:162)
    at sbt.internal.inc.IncrementalCompilerImpl$$anonfun$compileInternal$1.apply(IncrementalCompilerImpl.scala:162)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:78)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:76)
    at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:63)
    at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:37)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:73)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
    at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:101)
    at sbt.internal.inc.Incremental$.compile(Incremental.scala:71)
    at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:59)
    at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:162)
    at sbt.internal.inc.IncrementalCompilerImpl.incrementalCompile(IncrementalCompilerImpl.scala:107)
    at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:51)
    at sbt.Compiler$.compile(Compiler.scala:136)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:891)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:883)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:881)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
    at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:229)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:229)
    at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:229)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:229)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by romanowski** [comment]
I think this is caused by Class.getCanonicalName returning null for local or anonymous class: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/java/lang/Class.java?av=f#1214
In zinc code: https://github.com/sbt/zinc/blob/1.0/internal/zinc-apiinfo/src/main/scala/sbt/internal/inc/ClassToAPI.scala#L314

I think code like this should resolve problem (in last else):

``` scala
if (c.isArray) array(reference(c.getComponentType)) else if (c.isPrimitive) primitive(c.getName) 
else {
  val className = Option(c.getCanonicalName).getOrElse(c.getName)
  reference(className)
}
```
