### ISSUE TITLE
Analysis of javac compiled classes can cause static initializers to run

### ISSUE THREAD

**Issue by stuhood** [sbt/zinc#151]
Changes previously introduced to use the JDK reflection APIs (rather than only the classfile parser) cause static initializers in loaded classes to run (which is never desirable, as it sometimes has sideeffects).

To avoid this, we need to avoid using any APIs that cause classes to load.

```
java.lang.ExceptionInInitializerError
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.lang.Class.getEnumConstantsShared(Class.java:3320)
    at java.lang.Class.getEnumConstants(Class.java:3297)
    at sbt.internal.inc.ClassToAPI$.childrenOfSealedClass(ClassToAPI.scala:306)
    at sbt.internal.inc.ClassToAPI$.toDefinitions0(ClassToAPI.scala:76)
    at sbt.internal.inc.ClassToAPI$$anonfun$toDefinitions$1.apply(ClassToAPI.scala:68)
    at sbt.internal.inc.ClassToAPI$$anonfun$toDefinitions$1.apply(ClassToAPI.scala:68)
    at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
    at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
    at sbt.internal.inc.ClassToAPI$.toDefinitions(ClassToAPI.scala:68)
    at sbt.internal.inc.ClassToAPI$$anonfun$4.apply(ClassToAPI.scala:23)
    at sbt.internal.inc.ClassToAPI$$anonfun$4.apply(ClassToAPI.scala:23)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:23)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.sbt$internal$inc$javac$AnalyzingJavaCompiler$$readAPI$1(AnalyzingJavaCompiler.scala:81)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$5.apply(AnalyzingJavaCompiler.scala:91)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$5.apply(AnalyzingJavaCompiler.scala:91)
    at sbt.internal.inc.classfile.Analyze$$anonfun$apply$11.apply(Analyze.scala:65)
    at sbt.internal.inc.classfile.Analyze$$anonfun$apply$11.apply(Analyze.scala:60)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at sbt.internal.inc.classfile.Analyze$.apply(Analyze.scala:60)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2.apply(AnalyzingJavaCompiler.scala:91)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2$$anonfun$apply$mcV$sp$2.apply(AnalyzingJavaCompiler.scala:89)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply$mcV$sp(AnalyzingJavaCompiler.scala:89)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply(AnalyzingJavaCompiler.scala:89)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler$$anonfun$compile$2.apply(AnalyzingJavaCompiler.scala:89)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:100)
    at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:88)
```

**Comment by eed3si9n** [comment]
Is this the code around here?
- https://github.com/sbt/zinc/blob/1.0/zinc/src/main/scala/sbt/internal/inc/javac/AnalyzingJavaCompiler.scala
- https://github.com/sbt/zinc/blob/1.0/internal/zinc-apiinfo/src/main/scala/sbt/internal/inc/ClassToAPI.scala

Which change are we talking about?

**Comment by stuhood** [comment]
@eed3si9n : Something between `com.typesafe.sbt;incremental-compiler#0.13.9` and `org.scala-sbt;zinc#1.0.0-X1`... honestly, I suspect it is fallout from https://github.com/sbt/sbt/pull/2085, which we are just now attempting to incorporate.

**Comment by stuhood** [comment]
Updated original with a stack trace.

**Comment by romanowski** [comment]
@stuhood can you confirm that this is still a problem after https://github.com/sbt/zinc/pull/158 is merged? 

I faced similar problem and remove part of ClassToAPI that create new instances of enums classes in zinc runtime.

**Comment by stuhood** [comment]
Thanks @romanowski : @peiyuwang confirmed that this was fixed for us.
