### ISSUE TITLE
NoSuchElementException in TextAnalysisFormat

### ISSUE THREAD

**Issue by kiritsuku** [sbt/zinc#169]
I'm using zinc 1.0.0-X1. The error happened in a mixed Java+Scala project. I ran the built in Eclipse after doing a whitespace change to a Java file. The build finished successfully but the following exception was thrown afterwards:

```
2016-08-27 23:14:20,221 ERROR [main] - org.scala-ide.sdt.core - org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - Error in Scala compiler
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at sbt.internal.inc.TextAnalysisFormat$APIsF$$anonfun$23.apply(TextAnalysisFormat.scala:277)
        at sbt.internal.inc.TextAnalysisFormat$APIsF$$anonfun$23.apply(TextAnalysisFormat.scala:277)
        at xsbti.SafeLazy$Impl._t$lzycompute(SafeLazy.scala:18)
        at xsbti.SafeLazy$Impl._t(SafeLazy.scala:16)
        at xsbti.SafeLazy$Impl.get(SafeLazy.scala:22)
        at sbt.internal.inc.TextAnalysisFormat$APIsF$$anonfun$read$1$$anonfun$apply$2.apply(TextAnalysisFormat.scala:283)
        at sbt.internal.inc.TextAnalysisFormat$APIsF$$anonfun$read$1$$anonfun$apply$2.apply(TextAnalysisFormat.scala:283)
        at xsbti.SafeLazy$Impl._t$lzycompute(SafeLazy.scala:18)
        at xsbti.SafeLazy$Impl._t(SafeLazy.scala:16)
        at xsbti.SafeLazy$Impl.get(SafeLazy.scala:22)
        at xsbti.api.AnalyzedClass.api(AnalyzedClass.java:26)
        at sbt.internal.inc.TextAnalysisFormat$CompanionsF$$anonfun$28.apply(TextAnalysisFormat.scala:299)
        at sbt.internal.inc.TextAnalysisFormat$CompanionsF$$anonfun$28.apply(TextAnalysisFormat.scala:299)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at sbt.internal.inc.TextAnalysisFormat$CompanionsF$.write(TextAnalysisFormat.scala:299)
        at sbt.internal.inc.TextAnalysisFormat$.writeCompanionMap(TextAnalysisFormat.scala:99)
        at sbt.internal.inc.FileBasedStore$FileBasedStoreImpl$$anonfun$set$1.apply(FileBasedStore.scala:34)
        at sbt.internal.inc.FileBasedStore$FileBasedStoreImpl$$anonfun$set$1.apply(FileBasedStore.scala:28)
        at sbt.io.Using.apply(Using.scala:25)
        at sbt.internal.inc.FileBasedStore$FileBasedStoreImpl.set(FileBasedStore.scala:27)
        at sbt.internal.inc.AnalysisStore$$anon$1.set(AnalysisStore.scala:19)
        at sbt.internal.inc.AnalysisStore$$anon$2.set(AnalysisStore.scala:30)
        at org.scalaide.core.internal.builder.zinc.CachingCompiler.cacheAndReturnLastAnalysis(CachingCompiler.scala:62)
        at org.scalaide.core.internal.builder.zinc.CachingCompiler.compile(CachingCompiler.scala:55)
        at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.aggressiveCompile(EclipseSbtBuildManager.scala:212)
        at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.runCompiler(EclipseSbtBuildManager.scala:144)
        at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.update(EclipseSbtBuildManager.scala:126)
        at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.build(EclipseSbtBuildManager.scala:84)
        at org.scalaide.core.internal.project.scopes.BuildScopeUnit.build(BuildScopeUnit.scala:73)
        at org.scalaide.core.internal.project.SbtScopesBuildManager$$anonfun$build$1.apply(SbtScopesBuildManager.scala:54)
        at org.scalaide.core.internal.project.SbtScopesBuildManager$$anonfun$build$1.apply(SbtScopesBuildManager.scala:51)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalaide.core.internal.project.SbtScopesBuildManager.build(SbtScopesBuildManager.scala:51)
        at org.scalaide.core.internal.project.ScalaProject.build(ScalaProject.scala:603)
        at org.scalaide.core.internal.builder.ScalaBuilder.build(ScalaBuilder.scala:109)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
        at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:285)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by eed3si9n** [comment]
Do you have the repro steps?

**Comment by kiritsuku** [comment]
The concrete repro steps:
1. Create two empty classes. A Scala class `a.b.Class` and a Java class `a.b.JavaClass`.
2. Compile them once.
3. Make a whitespace change to one of these classes (changes probably only necessary in Eclipse because one can't recompile in Eclipse if there are no changes).
4. Compile again. The above error should be shown.

**Comment by eed3si9n** [comment]
Could you link to the Scala and Java sources plz, in case they matter?

**Comment by kiritsuku** [comment]
The sources are simple. The Scala file:

``` scala
package a.b

class Class {

}
```

And the Java file:

``` java
package a.b;

public class JavaClass {

}
```
