### ISSUE TITLE
ClassNotFoundException: xsbti.SafeLazy in 1.0.0-X10

### ISSUE THREAD

**Issue by kiritsuku** [sbt/zinc#260]
In zinc 1.0.0-X10, `xsbti.SafeLazy` has been renamed to `xsbti.api.SafeLazy`.

In scala-ide I get the following error at runtime:

```
java.lang.ClassNotFoundException: xsbti.SafeLazy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at xsbt.ExtractAPI.<init>(ExtractAPI.scala:144)
	at xsbt.API$ApiPhase.processScalaUnit(API.scala:36)
	at xsbt.API$ApiPhase.processUnit(API.scala:31)
	at xsbt.API$ApiPhase.apply(API.scala:29)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:416)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:409)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:380)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:380)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:380)
	at xsbt.API$ApiPhase.run(API.scala:24)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1418)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1403)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1398)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1492)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:129)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:108)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:259)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:132)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:79)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:130)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:70)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:113)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:288)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:288)
	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:90)
	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:74)
	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:80)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:47)
	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:74)
	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:117)
	at sbt.internal.inc.Incremental$.compile(Incremental.scala:72)
	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:63)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:288)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:252)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:156)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:235)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:143)
	at org.scalaide.core.internal.builder.zinc.CachingCompiler.compile(CachingCompiler.scala:54)
	at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.aggressiveCompile(EclipseSbtBuildManager.scala:213)
	at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.runCompiler(EclipseSbtBuildManager.scala:146)
	at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.update(EclipseSbtBuildManager.scala:128)
	at org.scalaide.core.internal.builder.zinc.EclipseSbtBuildManager.build(EclipseSbtBuildManager.scala:84)
	at org.scalaide.core.internal.project.scopes.BuildScopeUnit.build(BuildScopeUnit.scala:72)
	at org.scalaide.core.internal.project.SbtScopesBuildManager.$anonfun$build$3(SbtScopesBuildManager.scala:53)
	at org.scalaide.core.internal.project.SbtScopesBuildManager.$anonfun$build$3$adapted(SbtScopesBuildManager.scala:50)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at org.scalaide.core.internal.project.SbtScopesBuildManager.build(SbtScopesBuildManager.scala:50)
	at org.scalaide.core.internal.project.ScalaProject.build(ScalaProject.scala:596)
	at org.scalaide.core.internal.builder.ScalaBuilder.build(ScalaBuilder.scala:111)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:285)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

I can't tell if this an error in the IDE because we included a wrong version of a dependency or if this is a problem of zinc.

**Comment by jvican** [comment]
Hi @sschaef, yes, `SafeLazy` was moved and refactored into Java code, see [this](https://github.com/sbt/zinc/pull/221/commits/c1f821b1b37704618d54378c25a2464c8ad48a00) for the reasons.
  
It looks like you're not using the correct version of the compiler interface, since otherwise `xsbti.api.SafeLazy` should be there. Can you make sure this is the case and that you remove any stale class files?
  
I've tried Zinc 1.0 in sbt 0.13.13 and didn't get these issues, so I assume this is not an issue related to Zinc.

**Comment by kiritsuku** [comment]
Indeed, the compiler-interface is cached by the IDE. After removing and recompiling it, everything works well. Thanks!
