### ISSUE TITLE
different extra api hashes for no traits when compile Akka

### ISSUE THREAD

**Issue by He-Pin** [sbt/zinc#608]
```
[info] Compiling 1 Java source to /Users/kerr/IdeaProjects/akka/akka-cluster/target/test-classes ...
[info] Done compiling.
[error] java.lang.RuntimeException: A fatal error happened in `SameAPI`: different extra api hashes for no traits!
[error]   `akka.util.OptionVal`: 0
[error]   `akka.util.OptionVal`: 2116911007
[error]              
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at sbt.internal.inc.IncrementalNameHashing.sameAPI(IncrementalNameHashing.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.sameClass(IncrementalCommon.scala:204)
[error] 	at sbt.internal.inc.IncrementalCommon.$anonfun$changedIncremental$1(IncrementalCommon.scala:186)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:177)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at sbt.internal.inc.IncrementalCommon.changedIncremental(IncrementalCommon.scala:185)
[error] 	at sbt.internal.inc.IncrementalCommon.changedInitial(IncrementalCommon.scala:242)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:66)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (akka-actor-typed / Compile / compileIncremental) A fatal error happened in `SameAPI`: different extra api hashes for no traits!
[error]   `akka.util.OptionVal`: 0
[error]   `akka.util.OptionVal`: 2116911007
[error]              
[error] Total time: 26 s, completed 2018-10-13 16:12:52
```

**Comment by eed3si9n** [comment]
This is fixed in https://github.com/sbt/zinc/pull/606.
