### ISSUE TITLE
Under compilation of class that transitively extends trait which has had private field renamed

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#662]
Steps to reproduce in: https://github.com/retronym/zinc-test

```
$ git checkout 2d6edfb && sbt clean compile && git checkout 90072a9 && sbt compile c/console
Previous HEAD position was 90072a9 Rename private trait field a.A.{a1 => a2}
HEAD is now at 2d6edfb Add private field to trait a.A
[info] Loading settings for project global-plugins from idea.sbt,dirtymoney.sbt,gpg.sbt ...
[info] Loading global plugins from /Users/jz/.sbt/1.0/plugins
[info] Loading project definition from /Users/jz/code/zinc-test/project
[info] Loading settings for project zinc-test from build.sbt ...
[info] Set current project to zinc-test (in build file:/Users/jz/code/zinc-test/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed 01/05/2019 11:39:54 AM
[info] Updating ...
[info] Updating a...
[info] Done updating.
[info] Done updating.
[info] Updating b...
[info] Compiling 1 Scala source to /Users/jz/code/zinc-test/a/target/scala-2.12/classes ...
[info] Done updating.
[info] Updating c...
[info] Done updating.
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/jz/code/zinc-test/b/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/jz/code/zinc-test/c/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 2 s, completed 01/05/2019 11:39:56 AM
Previous HEAD position was 2d6edfb Add private field to trait a.A
HEAD is now at 90072a9 Rename private trait field a.A.{a1 => a2}
[info] Loading settings for project global-plugins from idea.sbt,dirtymoney.sbt,gpg.sbt ...
[info] Loading global plugins from /Users/jz/.sbt/1.0/plugins
[info] Loading project definition from /Users/jz/code/zinc-test/project
[info] Loading settings for project zinc-test from build.sbt ...
[info] Set current project to zinc-test (in build file:/Users/jz/code/zinc-test/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 1 Scala source to /Users/jz/code/zinc-test/a/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/jz/code/zinc-test/b/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed 01/05/2019 11:40:03 AM
[info] Starting scala interpreter...
Welcome to Scala 2.12.7 (OpenJDK 64-Bit Server VM, Java 1.8.0-adoptopenjdk).
Type in expressions for evaluation. Or try :help.

scala> new c.C
java.lang.AbstractMethodError: c.C.a$A$_setter_$a$A$$a2_$eq(Ljava/lang/String;)V
  at a.A.$init$(x.scala:4)
  at c.C.<init>(x.scala:3)
  ... 36 elided
```

**Comment by som-snytt** [comment]
It happened in presentation compiler tests in the linked PR, but I just hit it in code completion. It also happened after `clean ; dist/mkPack`. As in the linked PR, now I will `git clean -dfx` and try again. So, I wasn't losing my mind. These tests were of `build/pack/bin/scala`, not the `scala` task under `sbt` or `quick`.
```
scala> (0x7FFFFFF: Float).toInt.toH
Failed to initialize compiler: AbstractMethodError.
This is most often remedied by a full clean and recompile.
Otherwise, your classpath may continue bytecode compiled by
different and incompatible versions of scala.

java.lang.AbstractMethodError: Receiver class scala.tools.nsc.interactive.Global$$anon$4 does not define or inherit an implementation of the resolved method abstract scala$tools$nsc$typechecker$Contexts$_setter_$scala$tools$nsc$typechecker$Contexts$$TupleOfNullAndNoSymbol_$eq(Lscala/Tuple2;)V of interface scala.tools.nsc.typechecker.Contexts.
	at scala.tools.nsc.typechecker.Contexts.$init$(Contexts.scala:1881)
	at scala.tools.nsc.interactive.Global$$anon$4.<init>(Global.scala:228)
	at scala.tools.nsc.interactive.Global.analyzer$lzycompute(Global.scala:226)
	at scala.tools.nsc.interactive.Global.analyzer(Global.scala:226)
	at scala.tools.nsc.interactive.Global.analyzer(Global.scala:113)
	at scala.tools.nsc.Global.<init>(Global.scala:993)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:119)
	at scala.tools.nsc.interpreter.PresentationCompilation$$anon$2.<init>(PresentationCompilation.scala:75)
	at scala.tools.nsc.interpreter.PresentationCompilation.newPresentationCompiler(PresentationCompilation.scala:75)
	at scala.tools.nsc.interpreter.PresentationCompilation.newPresentationCompiler$(PresentationCompilation.scala:67)
	at scala.tools.nsc.interpreter.IMain.newPresentationCompiler(IMain.scala:72)
	at scala.tools.nsc.interpreter.PresentationCompilation.presentationCompile(PresentationCompilation.scala:36)
	at scala.tools.nsc.interpreter.PresentationCompilation.presentationCompile$(PresentationCompilation.scala:33)
	at scala.tools.nsc.interpreter.IMain.presentationCompile(IMain.scala:72)
	at scala.tools.nsc.interpreter.shell.ReplCompletion.codeCompletion(ReplCompletion.scala:73)
```
or
```
skala
Welcome to Scala 2.13.2-20200220-072627-3ec4bfe (OpenJDK 64-Bit Server VM, Java 11.0.3).
Type in expressions for evaluation. Or try :help.

scala> (0x7FFFFFF: Float).toInt.Exception in thread "Thread-1" java.lang.AbstractMethodError: Receiver class scala.tools.nsc.interactive.Global$$anon$4 does not define or inherit an implementation of the resolved method abstract scala$tools$nsc$typechecker$Contexts$_setter_$scala$tools$nsc$typechecker$Contexts$$TupleOfNullAndNoSymbol_$eq(Lscala/Tuple2;)V of interface scala.tools.nsc.typechecker.Contexts.
	at scala.tools.nsc.typechecker.Contexts.$init$(Contexts.scala:1881)
	at scala.tools.nsc.interactive.Global$$anon$4.<init>(Global.scala:228)
	at scala.tools.nsc.interactive.Global.analyzer$lzycompute(Global.scala:226)
	at scala.tools.nsc.interactive.Global.analyzer(Global.scala:226)
	at scala.tools.nsc.interactive.Global.analyzer(Global.scala:113)
	at scala.tools.nsc.Global.<init>(Global.scala:993)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:119)
```
