### ISSUE TITLE
MatchError when apiDebug is enabled and a `TraitPrivateMembersModified` api change is found

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#663]
```
[error] An exception has been thrown while trying to dump an api diff.
[error] scala.MatchError: TraitPrivateMembersModified(a.A) (of class sbt.internal.inc.TraitPrivateMembersModified)
[error] 	at sbt.internal.inc.IncrementalCommon.$anonfun$logApiChanges$1(IncrementalCommon.scala:156)
[error] 	at sbt.internal.inc.IncrementalCommon.$anonfun$logApiChanges$1$adapted(IncrementalCommon.scala:156)
[error] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
[error] 	at sbt.internal.inc.IncrementalCommon.logApiChanges(IncrementalCommon.scala:156)
[error] 	at sbt.internal.inc.IncrementalCommon.changedIncremental(IncrementalCommon.scala:190)
[error] 	at sbt.internal.inc.IncrementalCommon.changedInitial(IncrementalCommon.scala:242)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:66)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
```

Follow the steps in https://github.com/retronym/zinc-test, uncommenting the last two lines in `build.sbt` that enable logging.

**Comment by Friendseeker** [comment]
I failed to reproduce it with sbt 1.9.7. 

Also glanced the code and `logApiChanges` now do include a case for `TraitPrivateMembersModified`.

@SethTisue Would you mind to close the issue?
