### ISSUE TITLE
ci.scala-lang.org setting is gone

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#703]
https://ci.scala-lang.org seems to be missing the setting for sbt/zinc.

@jvican do you know what happened?

**Comment by eed3si9n** [comment]
I can see https://ci.scala-lang.org/sbt/zinc again, but it seems like it's failing on some Coursier locking issue?

```
[info] Loading settings for project zinc-build from plugins.sbt ...
[info] Loading project definition from /drone/src/github.com/sbt/zinc/project
[error] java.nio.file.FileAlreadyExistsException: /root/.coursier
[error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
[error] 	at java.nio.file.Files.createDirectory(Files.java:674)
[error] 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
[error] 	at java.nio.file.Files.createDirectories(Files.java:727)
[error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:124)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:553)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) java.nio.file.FileAlreadyExistsException: /root/.coursier
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by eed3si9n** [comment]
I guess it was fixed here? - https://github.com/coursier/coursier/pull/1389

**Comment by SethTisue** [comment]
Looks like this was intended to be closed.
