### ISSUE TITLE
Scaladoc may generate bad position

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#734]
https://github.com/sbt/zinc/pull/571 seems to interact poorly with Scaladoc. I think the root bug is in Scaladoc which is spitting out an invalid end position for use cases.

## steps

git clone https://github.com/retronym/sbt-scaladoc-aioooe

Then add

### Base.scala

```scala
package demo

abstract class Base
```

### StringOps.scala

```scala
package demo

/**
 *  @usecase  def sameElements(that: GenIterable[A]): Boolean
 */
abstract class StringOps extends demo.Base
```

Then run `doc`.

## problem

```
[info] Main Scala API documentation to /Users/jz/code/sbt-scaladoc-aioooe/target/scala-2.13/api...
[error] java.lang.ArrayIndexOutOfBoundsException: 14
[error] 	at scala.reflect.internal.util.BatchSourceFile.findLine$1(SourceFile.scala:200)
[error] 	at scala.reflect.internal.util.BatchSourceFile.offsetToLine(SourceFile.scala:203)
[error] 	at xsbt.DelegatingReporter$.lineOf$1(DelegatingReporter.scala:99)
[error] 	at xsbt.DelegatingReporter$.makePosition$1(DelegatingReporter.scala:112)
[error] 	at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:134)
[error] 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:165)
[error] 	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
[error] 	at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
[error] 	at scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:118)
[error] 	at scala.reflect.internal.Reporter.warning(Reporting.scala:112)
[error] 	at scala.tools.nsc.doc.ScaladocAnalyzer$ScaladocTyper.$anonfun$typedDocDef$1(ScaladocAnalyzer.scala:47)
[error] 	at scala.tools.nsc.doc.ScaladocAnalyzer$ScaladocTyper.typedDocDef(ScaladocAnalyzer.scala:44)
[error] 	at scala.tools.nsc.doc.ScaladocAnalyzer$ScaladocTyper.typedDocDef$(ScaladocAnalyzer.scala:36)
```

Zinc could guard against the dodgy positions here. I'll see if I can figure out how to fix the positions in Scaladoc itself.

_Originally posted by @retronym in https://github.com/sbt/zinc/pull/571#issuecomment-578467052_

**Comment by dwijnand** [comment]
upstream: https://github.com/scala/bug/issues/11865
