### ISSUE TITLE
Error compiling the sbt component 'compiler-bridge_2.11'

### ISSUE THREAD

**Issue by ericbellet** [sbt/zinc#737]
I am using scalaVersion_ = "2.11.8"

build.sbt
```
lazy val commonDependencies = Seq(
  "org.apache.spark" %% "spark-sql" % sparkVersion
  ,"com.databricks" %% "dbutils-api" % "0.0.3"
  ,"com.microsoft.azure" % "applicationinsights-core" % "2.5.0"
  ,"com.microsoft.azure" % "applicationinsights-web" % "2.5.0"
)

lazy val commonSettings = Seq(
  scalaVersion := scalaVersion_
)
```

I received the next error and I would like to know how to fit it

```
[info] Non-compiled module 'compiler-bridge_2.11' for Scala 2.11.8. Compiling...
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
        at scala.tools.nsc.Driver.process(Driver.scala:51)
        at scala.tools.nsc.Main.process(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:56)
        at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:77)
        at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$6(AnalyzingCompiler.scala:363)
        at sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:338)
        at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4(AnalyzingCompiler.scala:359)
        at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4$adapted(AnalyzingCompiler.scala:354)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
        at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2(AnalyzingCompiler.scala:354)
        at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2$adapted(AnalyzingCompiler.scala:346)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
        at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:346)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:261)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:250)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:250)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:119)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:250)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:247)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
        at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:247)
        at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:215)
        at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
        at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
        at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
        at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
        at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
        at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
        at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
        at scala.Option.map(Option.scala:230)
        at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
        at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
        at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
        at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
        at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
        at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
        at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
        at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
        at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
        at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:215)
        at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:75)
        at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:81)
        at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
        at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
        at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
        at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:145)
        at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:132)
        at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:102)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
        at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
        at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
        at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
        at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
        at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
        at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
        at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
        at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
        at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
        at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
        at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
        at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
        at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
        at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
        at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
        at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1761)
        at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1734)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
        at sbt.std.Transform$$anon$4.work(Transform.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
        at sbt.Execute.work(Execute.scala:290)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.11:1.3.1.
[error] (commonsUtils / Compile / compileIncremental) Error compiling the sbt component 'compiler-bridge_2.11'
[error] Total time: 4 s, completed Feb 7, 2020, 11:51:53 AM
[IJ]sbt:etl.gold.corrosion.internal>
[IJ]sbt:etl.gold.corrosion.internal>
Process finished with exit code 1
```

**Comment by SethTisue** [comment]
what if you use 2.11.12 instead of 2.11.8?

what JDK version are you on?

what sbt version are you using? (not sure, but it looks like you might be using 1.3.1? if so, have you tried using 1.3.8 instead?)

**Comment by ericbellet** [comment]
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode).


I am using the 2.11.8 because the project was build with that version. About the sbt version I am not pretty sure of how to see the version, I just installed the Scala plugin on IntellijIdea 
![image](https://user-images.githubusercontent.com/11494509/74137096-817de580-4bef-11ea-8193-7548d3f8c889.png) but I don't know how to see the Sbt version

**Comment by eed3si9n** [comment]
I don't think this is a Zinc bug. We use GitHub issue mostly to track bugs and discuss feature or bugs on sbt. If you need help, please check this out - https://www.scala-sbt.org/support.html#how-can-I-get-help

From the stacktrace IntelliJ is using JDK 9 or above, and you need Scala 2.11.12 for that - https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by SethTisue** [comment]
this now under discussion at https://stackoverflow.com/questions/60101210/error-compiling-the-sbt-component-compiler-bridge-2-11
