### ISSUE TITLE
Scripted doesn't show logs

### ISSUE THREAD

**Issue by gkossakowski** [sbt/zinc#82]
When I have a failing test, I see a long stacktace (that in itself is unhelpful):

```
[error] x source-dependencies / check-products
sbt.internal.scripted.TestException: {line 2}  Command failed
    at sbt.internal.scripted.ScriptRunner.sbt$internal$scripted$ScriptRunner$$processStatement$1(ScriptRunner.scala:25)
    at sbt.internal.scripted.ScriptRunner$$anonfun$apply$2.apply(ScriptRunner.scala:40)
    at sbt.internal.scripted.ScriptRunner$$anonfun$apply$2.apply(ScriptRunner.scala:40)
    at scala.Function$$anonfun$tupled$1.apply(Function.scala:77)
    at scala.Function$$anonfun$tupled$1.apply(Function.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at sbt.internal.scripted.ScriptRunner.apply(ScriptRunner.scala:40)
    at sbt.internal.scripted.ScriptedTests.runTest$1(ScriptedTests.scala:98)
    at sbt.internal.scripted.ScriptedTests.sbt$internal$scripted$ScriptedTests$$scriptedTest(ScriptedTests.scala:107)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ScriptedTests.scala:65)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ScriptedTests.scala:59)
    at sbt.internal.io.Resources.sbt$internal$io$Resources$$readWrite$1(Resources.scala:58)
    at sbt.internal.io.Resources$$anonfun$readWriteResourceDirectory$1.apply(Resources.scala:60)
    at sbt.internal.io.Resources$$anonfun$readWriteResourceDirectory$1.apply(Resources.scala:60)
    at sbt.io.IO$.withTemporaryDirectory(IO.scala:292)
    at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:60)
    at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:48)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3.apply(ScriptedTests.scala:59)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3.apply(ScriptedTests.scala:57)
    at sbt.internal.scripted.ScriptedRunnerImpl$$anonfun$2.apply(ScriptedTests.scala:23)
    at sbt.internal.scripted.ScriptedRunnerImpl$$anonfun$2.apply(ScriptedTests.scala:23)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at sbt.internal.scripted.ScriptedRunnerImpl$.runAll(ScriptedTests.scala:23)
    at sbt.internal.scripted.ScriptedRunnerImpl$.run(ScriptedTests.scala:20)
    at sbt.internal.inc.IncScriptedRunner.run(IncScriptedRunner.scala:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at Scripted$.doScripted(Scripted.scala:74)
    at $a46f601819c93f1e9459$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:264)
    at $a46f601819c93f1e9459$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:261)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: Set("A", "A$") did not equal Set("A") Expected Set(A, A$) products, got Set(A)
    at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
    at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1683)
    at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
    at sbt.internal.inc.IncHandler.assertClasses$1(IncHandler.scala:146)
    at sbt.internal.inc.IncHandler.checkProducts(IncHandler.scala:148)
    at sbt.internal.inc.IncHandler$$anonfun$commands$5.apply(IncHandler.scala:72)
    at sbt.internal.inc.IncHandler$$anonfun$commands$5.apply(IncHandler.scala:69)
    at sbt.internal.inc.IncHandler$$anonfun$apply$1.apply(IncHandler.scala:186)
    at sbt.internal.inc.IncHandler$$anonfun$apply$1.apply(IncHandler.scala:185)
    at sbt.internal.inc.IncHandler.onIncInstance(IncHandler.scala:192)
    at sbt.internal.inc.IncHandler.apply(IncHandler.scala:185)
    at sbt.internal.inc.IncHandler.apply(IncHandler.scala:24)
    at sbt.internal.scripted.ScriptRunner.sbt$internal$scripted$ScriptRunner$$processStatement$1(ScriptRunner.scala:18)
    ... 53 more
```

Running `last` doesn't help to reveal what's the true problem:

```
> last incrementalcompilerRoot/*:scripted
java.lang.RuntimeException: Failed tests:
    source-dependencies / check-products

    at scala.sys.package$.error(package.scala:27)
    at sbt.internal.scripted.ScriptedRunnerImpl$.runAll(ScriptedTests.scala:25)
    at sbt.internal.scripted.ScriptedRunnerImpl$.run(ScriptedTests.scala:20)
    at sbt.internal.inc.IncScriptedRunner.run(IncScriptedRunner.scala:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at Scripted$.doScripted(Scripted.scala:74)
    at $a46f601819c93f1e9459$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:264)
    at $a46f601819c93f1e9459$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:261)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (incrementalcompilerRoot/*:scripted) Failed tests:
[error]     source-dependencies / check-products
```

In particular, I'd expect `last` to show incremental compiler debug logs but nothing seems to be logged.

**Comment by gkossakowski** [comment]
@Duhemm, is this a known problem?

**Comment by eed3si9n** [comment]
@gkossakowski isn't this the problem?

```
Caused by: org.scalatest.exceptions.TestFailedException: Set("A", "A$") did not equal Set("A") Expected Set(A, A$) products, got Set(A)
    at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
    at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1683)
    at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
    at sbt.internal.inc.IncHandler.assertClasses$1(IncHandler.scala:146)
    at sbt.internal.inc.IncHandler.checkProducts(IncHandler.scala:148)
    at sbt.internal.inc.IncHandler$$anonfun$commands$5.apply(IncHandler.scala:72)
    at sbt.internal.inc.IncHandler$$anonfun$commands$5.apply(IncHandler.scala:69)
    at sbt.internal.inc.IncHandler$$anonfun$apply$1.apply(IncHandler.scala:186)
    at sbt.internal.inc.IncHandler$$anonfun$apply$1.apply(IncHandler.scala:185)
    at sbt.internal.inc.IncHandler.onIncInstance(IncHandler.scala:192)
    at sbt.internal.inc.IncHandler.apply(IncHandler.scala:185)
    at sbt.internal.inc.IncHandler.apply(IncHandler.scala:24)
    at sbt.internal.scripted.ScriptRunner.sbt$internal$scripted$ScriptRunner$$processStatement$1(ScriptRunner.scala:18)
    ... 53 more
```

**Comment by gkossakowski** [comment]
Yes, it shows the failing assertion but the problem is that there are no logs of incremental compiler activity so you cannot figure out what led to failing assertion.
In sbt/sbt, you can add `logLevel := Level.Debug` to `build.sbt` and scripted will redirect anything sbt prints to console. There's no equivalent zinc's scripted.

**Comment by eed3si9n** [comment]
If it's not there already, let's add `> debug` command to show the debug logs.

**Comment by gkossakowski** [comment]
My suggestion is that you redirect what incremental compiler logs at the `Debug` level to to `Debug` level of scripted. This way you can just run `last` to see the full log (or change sbt's log level of the `scripted` command).

**Comment by gkossakowski** [comment]
The manual enabling of debug logging in sbt/sbt's scripted is an annoyance and not a feature.

**Comment by eed3si9n** [comment]
I see https://github.com/sbt/zinc/blob/1.0/internal/incrementalcompiler-scripted/src/test/scala/sbt/internal/inc/IncHandler.scala#L170 so it can't be too far off from what you are suggesting.

**Comment by gkossakowski** [comment]
Yeah, I saw that. I don't understand why it's not working the way I described. Hence I consider this a bug :)

**Comment by eed3si9n** [comment]
Well there's also this - https://github.com/sbt/zinc/blob/1.0/project/Scripted.scala#L66-L76

**Comment by smarter** [comment]
I had to comment this line to get logs to show up: https://github.com/sbt/zinc/blob/2529bbd58e458bc7c09fa1931faa09559e584372/internal/incrementalcompiler-ivy-integration/src/test/scala/sbt/internal/inc/BridgeProviderSpecification.scala#L20 introduced by this commit: https://github.com/sbt/zinc/commit/de711221a772e8a015e1b8abfaf8cf19ab1a3a48
I'd rather have verbose logs than miss messages when debugging.

**Comment by smarter** [comment]
In fact, removing the line is not enough, you need to replace it by `log.setLevel(Level.Debug)`

**Comment by smarter** [comment]
After the merge of #93 I now have no idea what to do to get scripted to display the incremental compiler debug logs, could someone please give a step-by-step guide?

**Comment by gkossakowski** [comment]
Ooops, my bad. I forgot about complementary fixes in sbt/util module. See sbt/util#38.
Until the new release of sbt/util is out, it can used locally this way:
1. Checkout sbt/util with my PR merged (or my branch) and publish locally
2. Apply

``` patch
diff --git a/project/Dependencies.scala b/project/Dependencies.scala
index 4fa0a06..34df27d 100644
--- a/project/Dependencies.scala
+++ b/project/Dependencies.scala
@@ -9,7 +9,7 @@ object Dependencies {
   val scala211 = "2.11.7"

   val bootstrapSbtVersion = "0.13.8"
-  val utilVersion = "0.1.0-M8"
+  val utilVersion = "0.1.0-M10-9f9ac3a9ccbf0a9b8c51b6c237ccd4697a5d08fd"

   lazy val sbtIO = "org.scala-sbt" %% "io" % "1.0.0-M3"
   lazy val utilLogging = "org.scala-sbt" %% "util-logging" % utilVersion
```

to sbt/zinc
